import type { Metadata } from "next";
import { Marcellus_SC } from "next/font/google";
import "./globals.css";

const marcellus = Marcellus_SC({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className={`${marcellus.className} min-h-full flex flex-col text-white`}>
        <p> The Power of Stock Market </p>
        {children}
      </body>
    </html>
  );
}